### PR TITLE
Remove license file

### PR DESCRIPTION
**Pull request by ericpre**
Remove LICENSE.txt file since it is now included in the source distribution to avoid error with constructor.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cmeyer** [comment]
I don't think we should make this change yet. See https://github.com/nion-software/nionui/commit/731cafe81359695e532181fe1a35bf91f2bdf754.

**Comment by cmeyer** [comment]
The problem is that with my 'data_files' technique, the license is installed to a common location in the environment; and can easily be overwritten by other packages that use the same line of code.

**Comment by cmeyer** [comment]
Also, see this from the official conda-forge docs.

[Packaging the License Manually](https://conda-forge.readthedocs.io/en/latest/meta.html#packaging-the-license-manually)

**Comment by ericpre** [comment]
> I don't think we should make this change yet. See nion-software/nionui@731cafe.

Are you implying that the license will not be included in the source distribution?

> Also, see this from the official conda-forge docs.
>
> Packaging the License Manually

From the conda-forge docs:
"This means that the about/license_file entry must be included in the meta.yaml. Unfortunately, the license isn’t always included in the tarball of the source code."

If the license is included in the source distribution (as it is in the last release), then it is fine... Obviously, the right fix is to include it in the source distribution including on pypi. Maybe worth giving a try at the alternative approach mentioned in https://github.com/nion-software/nionui/pull/26.

xref https://github.com/conda-forge/nionui-feedstock/issues/1

**Comment by cmeyer** [comment]
Ok I see -- yes this PR looks good to me. Thanks!

**Pull request merged**
